export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const REGISTER_MODAL_IS_OPEN = 'REGISTER_MODAL_IS_OPEN';
export const GET_EV_DATA = 'GET_EV_DATA'
export const GET_RECIPE_DATA = 'GET_RECIPE_DATA';